[platformio]
default_envs =
    esp8266_biometric_monitor
    esp32_sleep_stage_alarm

[env]
framework = arduino
monitor_speed = 115200

[env:esp8266_biometric_monitor]
platform = espressif8266
board = nodemcuv2
build_flags =
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif8266/libraries/SPI"
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif8266/libraries/ESP8266WiFi/src"
build_src_filter =
    -<*>
    +<biometric_monitor.cpp>
lib_deps =
    file://./Biometric Monitor/lib/MAX30100_PulseOximeter/Arduino-MAX30100-master
    adafruit/Adafruit MLX90614 Library
    knolleary/PubSubClient
    mathworks/ThingSpeak

[env:esp32_sleep_stage_alarm]
platform = espressif32
board = esp32dev
build_flags =
    -I"$PROJECT_PACKAGES_DIR/framework-arduinoespressif32/libraries/BluetoothSerial/src"
build_src_filter =
    -<*>
    +<sleep_stage_alarm.cpp>
lib_deps =
    file://./Biometric Monitor/lib/MAX30100_PulseOximeter/Arduino-MAX30100-master
    rfetick/MPU6050_light
